services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    restart: unless-stopped

    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:80"   # local web access

    environment:
      TZ: "Europe/Dublin"
      FTLCONF_webserver_api_password: "CHANGE_ME_STRONG_PASSWORD"
      FTLCONF_dns_listeningMode: "all"

    volumes:
      - /mnt/tank/docker/dns/pihole/config:/etc/pihole

    networks:
      - proxy
      - default

networks:
  proxy:
    external: true
