services:
  nextcloud-aio-mastercontainer:
    image: ghcr.io/nextcloud-releases/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    init: true
    restart: unless-stopped

    ports:
      - "8080:8080"   # AIO admin interface
      # Do not publish 80/443 here when Traefik handles public web traffic

    environment:
      APACHE_PORT: 11000
      #APACHE_ADDITIONAL_NETWORK: traefik_proxy
      # OPTIONAL:
      NEXTCLOUD_DATADIR: /mnt/tank/nextcloud_aio
      # NEXTCLOUD_MOUNT: /mnt/
      SKIP_DOMAIN_VALIDATION: false

    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

networks:
  proxy:
    external: true